// this code is autogenerated, do not check it into to your code repository

// ref lib/aether/native/scanner.ex:12
const beam = @import("beam");
const std = @import("std");

/// Flawless Directory Scanner
/// Uses the BEAM allocator to ensure zero-leak stability.
pub fn scan_directory(path: []const u8) !beam.term {
    // Industrial Safety: We handle the path as a slice
    var dir = std.fs.cwd().openDir(path, .{ .iterate = true }) catch |err| {
        return beam.make_error_pair(@errorName(err));
    };
    defer dir.close();

    // Placeholder for high-speed indexing logic
    return beam.make_ok_pair(beam.make_slice(path));
}
